# Generated by Django 5.1.5 on 2025-02-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbl', models.TextField(max_length=13, verbose_name='HBL')),
                ('addressee', models.TextField(max_length=300, verbose_name='Destinatario')),
                ('identify_number', models.TextField(max_length=11, verbose_name='Carnet de Identidad')),
                ('phone_number', models.TextField(max_length=30, verbose_name='Numero Telefonico')),
                ('address', models.TextField(max_length=300, verbose_name='Direccion')),
                ('city', models.TextField(max_length=100, verbose_name='Municipio')),
                ('state', models.TextField(max_length=30, verbose_name='Provincia')),
                ('tariff', models.FloatField(verbose_name='Arancel')),
                ('transfer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.transfer')),
            ],
        ),
    ]
