# Generated by Django 5.1.5 on 2025-02-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_packagestransfer_transference'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='transfer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.transference'),
        ),
    ]
