# Generated by Django 5.1.5 on 2025-02-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='hbl',
            field=models.TextField(max_length=13, unique=True, verbose_name='HBL'),
        ),
    ]
