# Generated by Django 5.1.5 on 2025-02-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehouse_hbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='identify_number',
            new_name='ci',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='addressee',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='transfer_id',
        ),
    ]
