# Generated by Django 5.1.5 on 2025-02-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_identify_number_warehouse_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='hbl',
            field=models.TextField(max_length=13, verbose_name='HBL'),
        ),
    ]
