# Generated by Django 5.1.5 on 2025-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_warehouse_transference_id_warehousesimplified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='transference_id',
            field=models.TextField(null=True, verbose_name='ID Transferencia'),
        ),
        migrations.AlterField(
            model_name='warehousesimplified',
            name='transference_id',
            field=models.TextField(null=True, verbose_name='ID Transferencia'),
        ),
    ]
