# Generated by Django 5.1.5 on 2025-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_rename_tarriff_clients_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=13, verbose_name='Nombre de la ruta')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
    ]
