# Generated by Django 5.1.5 on 2025-02-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(verbose_name='Nombre del chofer')),
                ('license', models.TextField(max_length=11, verbose_name='Numero de licencia')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('model', models.TextField(verbose_name='Modelo del vehiculo')),
                ('matriculate', models.TextField(max_length=7, verbose_name='Matricula')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.vehicle'),
        ),
    ]
