# Generated by Django 5.1.5 on 2025-02-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_driver_vehicle_shipment_driver_shipment_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Nombre del chofer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.TextField(max_length=30, verbose_name='Modelo del vehiculo'),
        ),
    ]
