# Generated by Django 5.1.5 on 2025-02-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_status'),
        ('shipment', '0006_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Clientes'),
        ),
    ]
