# Generated by Django 5.1.5 on 2025-02-18 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_alter_shipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
