# Generated by Django 5.1.5 on 2025-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_remove_shipment_clients_shipment_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.TextField(max_length=14, unique=True, verbose_name='Nombre de la ruta'),
        ),
    ]
