# Generated by Django 5.1.5 on 2025-02-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0013_alter_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
