# Generated by Django 5.1.5 on 2025-02-22 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0014_alter_shipment_id'),
        ('warehouse', '0005_alter_warehouse_hbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='clients',
            field=models.ManyToManyField(to='warehouse.warehouse', verbose_name='Clientes'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
