# Generated by Django 5.1.5 on 2025-02-13 18:22

import clients.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbl', models.TextField(verbose_name='Codigo de Envio')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('name', models.TextField(verbose_name='Nombre y Apellidos')),
                ('ci', models.TextField(verbose_name='Carnet de Identidad')),
                ('phone', models.TextField(verbose_name='Telefono')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('province', models.TextField(verbose_name='Provincia')),
                ('city', models.TextField(verbose_name='Provincia')),
                ('tarriff', models.FloatField(verbose_name='Arancel')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=clients.models.rename_file, verbose_name='Manifiesto')),
            ],
        ),
    ]
