# Generated by Django 5.1.5 on 2025-02-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='tarriff',
            new_name='tariff',
        ),
    ]
