# Generated by Django 5.1.5 on 2025-02-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_tarriff_clients_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.TextField(default='Enviado', verbose_name='Estado'),
        ),
    ]
