# Generated by Django 5.1.5 on 2025-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('hbl', models.TextField(max_length=13, verbose_name='HBL')),
                ('addressee', models.TextField(max_length=300, verbose_name='Destinatario')),
                ('identify_number', models.TextField(max_length=11, verbose_name='Carnet de Identidad')),
                ('phone_number', models.TextField(max_length=30, verbose_name='Numero Telefonico')),
                ('address', models.TextField(max_length=300, verbose_name='Direccion')),
                ('city', models.TextField(max_length=100, verbose_name='Municipio')),
                ('state', models.TextField(max_length=30, verbose_name='Provincia')),
                ('bl', models.TextField(max_length=20, verbose_name='Codigo de Envio')),
            ],
        ),
    ]
