# Generated by Django 5.1.5 on 2025-02-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_packagestransfer_transference'),
        ('warehouse', '0002_alter_warehouse_transfer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
