# Generated by Django 5.1.5 on 2025-02-08 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_transference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transference',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 8, 20, 55, 59, 819525), verbose_name='Fecha'),
        ),
    ]
