# Generated by Django 5.1.5 on 2025-02-09 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_transference_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=30, verbose_name='Nombre'),
        ),
    ]
