# Generated by Django 5.1.5 on 2025-02-09 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_transference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
