# Generated by Django 5.1.5 on 2025-02-09 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_alter_transference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='name',
            field=models.TextField(default=uuid.uuid4, max_length=30, verbose_name='Nombre'),
        ),
    ]
