# Generated by Django 5.1.5 on 2025-02-09 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_alter_transference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha'),
        ),
    ]
