# Generated by Django 5.1.5 on 2025-02-09 14:37

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_alter_transference_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 14, 37, 16, 472201, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='transference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ebf8fa4-bdc3-47a9-bf50-6d0de2a34753'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transference',
            name='name',
            field=models.TextField(default=uuid.UUID('b7f7bc0e-1a2a-4764-9e5c-e456606459b4'), max_length=30, verbose_name='Nombre'),
        ),
    ]
