# Generated by Django 5.1.5 on 2025-02-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_alter_transference_date_alter_transference_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transference',
            name='packages',
        ),
    ]
