# Generated by Django 5.1.5 on 2025-02-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_remove_transference_packages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackagesTransfer',
        ),
    ]
