# Generated by Django 5.1.5 on 2025-03-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0015_delete_packagestransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='name',
            field=models.TextField(default='DT-Transfer-', max_length=36, verbose_name='Nombre'),
        ),
    ]
